tasks:
    -   init: |
            sdk install java 21.0.8-tem < /dev/null
            sdk install java 11.0.26-tem < /dev/null

vscode:
    extensions:
        - ms-vscode-remote.remote-containers
        - ms-azuretools.vscode-docker
        - vscjava.vscode-java-pack
